import type { Authorization } from './types';

export const authorizations: Authorization[] = [
  {
    id: '1',
    nomeAluno: 'João Silva',
    idade: 8,
    serie: '3º Ano',
    turno: 'Manhã',
    escola: 'Escola Primária Sol Nascente',
    nomeResponsavel: 'Maria Silva',
    telefone: '(11) 98765-4321',
    status: 'pendente',
    dataCadastro: new Date('2024-07-20T10:00:00Z').toISOString(),
    criadoPor: 'sistema',
    atualizadoEm: new Date().toISOString(),
  },
  {
    id: '2',
    nomeAluno: 'Ana Pereira',
    idade: 7,
    serie: '2º Ano',
    turno: 'Tarde',
    escola: 'Colégio Aprender Mais',
    nomeResponsavel: 'Carlos Pereira',
    telefone: '(21) 91234-5678',
    status: 'pendente',
    dataCadastro: new Date('2024-07-21T11:30:00Z').toISOString(),
    criadoPor: 'sistema',
    atualizadoEm: new Date().toISOString(),
  },
  {
    id: '3',
    nomeAluno: 'Lucas Souza',
    idade: 9,
    serie: '4º Ano',
    turno: 'Manhã',
    escola: 'Escola Primária Sol Nascente',
    nomeResponsavel: 'Fernanda Souza',
    telefone: '(31) 99999-8888',
    status: 'liberado',
    dataCadastro: new Date('2024-07-19T09:00:00Z').toISOString(),
    dataLiberacao: new Date('2024-07-22T14:00:00Z').toISOString(),
    criadoPor: 'coordenacao',
    atualizadoEm: new Date().toISOString(),
  },
  {
    id: '4',
    nomeAluno: 'Beatriz Santos',
    idade: 8,
    serie: '3º Ano',
    turno: 'Tarde',
    escola: 'Colégio Estrela Guia',
    nomeResponsavel: 'Ricardo Santos',
    telefone: '(41) 98888-7777',
    status: 'liberado',
    dataCadastro: new Date('2024-07-18T15:00:00Z').toISOString(),
    dataLiberacao: new Date('2024-07-22T14:05:00Z').toISOString(),
    criadoPor: 'coordenacao',
    atualizadoEm: new Date().toISOString(),
  },
  {
    id: '5',
    nomeAluno: 'Gabriel Costa',
    idade: 10,
    serie: '5º Ano',
    turno: 'Manhã',
    escola: 'Colégio Aprender Mais',
    nomeResponsavel: 'Juliana Costa',
    telefone: '(51) 97777-6666',
    status: 'agendado',
    dataCadastro: new Date('2024-07-17T08:45:00Z').toISOString(),
    dataLiberacao: new Date('2024-07-20T16:00:00Z').toISOString(),
    dataAgendamento: new Date(new Date().setDate(new Date().getDate() + 1)).toISOString(),
    horaAgendamento: '10:30',
    atendenteId: 'tele_01',
    observacoes: 'Mãe confirmou presença.',
    criadoPor: 'telemarketing',
    atualizadoEm: new Date().toISOString(),
  },
  {
    id: '6',
    nomeAluno: 'Mariana Oliveira',
    idade: 6,
    serie: '1º Ano',
    turno: 'Tarde',
    escola: 'Escola Primária Sol Nascente',
    nomeResponsavel: 'Rafael Oliveira',
    telefone: '(61) 96666-5555',
    status: 'agendado',
    dataCadastro: new Date('2024-07-16T13:20:00Z').toISOString(),
    dataLiberacao: new Date('2024-07-19T18:00:00Z').toISOString(),
    dataAgendamento: new Date(new Date().setDate(new Date().getDate() + 2)).toISOString(),
    horaAgendamento: '14:00',
    atendenteId: 'tele_02',
    criadoPor: 'telemarketing',
    atualizadoEm: new Date().toISOString(),
  },
    {
    id: '7',
    nomeAluno: 'Felipe Almeida',
    idade: 8,
    serie: '3º Ano',
    turno: 'Manhã',
    escola: 'Colégio Estrela Guia',
    nomeResponsavel: 'Sandra Almeida',
    telefone: '(71) 95555-4444',
    status: 'compareceu',
    dataCadastro: new Date('2024-07-15T09:10:00Z').toISOString(),
    dataLiberacao: new Date('2024-07-18T10:00:00Z').toISOString(),
    dataAgendamento: new Date(new Date().setDate(new Date().getDate() - 1)).toISOString(),
    horaAgendamento: '09:00',
    atendenteId: 'tele_01',
    observacoes: 'Chegou 10 minutos adiantado.',
    criadoPor: 'telemarketing',
    atualizadoEm: new Date().toISOString(),
  },
  {
    id: '8',
    nomeAluno: 'Larissa Lima',
    idade: 7,
    serie: '2º Ano',
    turno: 'Tarde',
    escola: 'Colégio Aprender Mais',
    nomeResponsavel: 'Bruno Lima',
    telefone: '(81) 94444-3333',
    status: 'nao_compareceu',
    dataCadastro: new Date('2024-07-14T16:00:00Z').toISOString(),
    dataLiberacao: new Date('2024-07-17T11:00:00Z').toISOString(),
    dataAgendamento: new Date(new Date().setDate(new Date().getDate())).toISOString(),
    horaAgendamento: '15:30',
    atendenteId: 'tele_02',
    observacoes: 'Telefone não atende para confirmar.',
    criadoPor: 'telemarketing',
    atualizadoEm: new Date().toISOString(),
  },
];
